# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Build settings
#@@@TODO
##remote_theme: iamlynnmkcay/jekyll-theme-iamlynnmckay@v0.1.0
##plugins:
##  - jekyll-remote-theme
##theme: "jekyll-theme-iamlynnmckay"
theme: "minima"
#plugins:
#  - jekyll-feed

# config
show_email: false
show_excepts: false
show_tags: true
show_header: true
show_footer: false
show_links_on_homepage: false
show_links_in_header: false
show_posts: true


# minima
email: 
baseurl: "" 
twitter_username: iamlynnmckay
github_username:  iamlynnmckay

# jekyll-seo-tag 
author: "Lynn McKay"
url: "https://iamlynnmckay.com"
title: "@iamlynnmckay"
description: "Lynn's blog about things and stuff."
twitter:
  username: "iamlynnmckay"
  card: "site.twitter.card"
logo: "assets/images/logo.svg"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
